### ISSUE TITLE
[Task] 회원 관리 서비스 소스 업로드

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#1]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 회원 관리 서비스 소스 공유

# TODO
1. [x] 프로젝트 기반 활용
2. [x] DB > master & slave 연결
3. [x] gitignore > 보안을 위해 YAML 파일은 제외 등록

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `FE`, `BE`
- Sprint: `회원 관리 서비스 개발 Sprint`
- Urgency: `High`
