### ISSUE TITLE
[Task] 회원가입 페이지 UI 개발

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#10]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 회원가입 페이지 UI 개발

# TODO
1. [X] 사용자의 정보를 입력받을 수 있도록 입력 폼 구현
2. [X] 회원 가입을 진행할 수 있도록 완료 버튼 구현
3. [X] 회원 정보 유효성 검사 구현

# 소요 시간
### Labels
- Estimated time: `E: 1.5h`
- Group : `FE`
- Sprint: `회원가입 페이지 UI 개발`
- Urgency: `High`
