### ISSUE TITLE
[Task] 설정 페이지 UI 개발

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#12]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 설정 페이지 UI 개발

# TODO
1. [X] 마이페이지로 이동할 수 있는 버튼 구현
2. [X] 로그아웃을 진행할 수 있도록 버튼 구현
3. [X] 이용 약관 및 정책을 확인할 수 있도록 버튼 구현
4. [X] 회원탈퇴를 진행할 수 있도록 버튼 구현

# 소요 시간
### Labels
- Estimated time: `E: 1h`
- Group : `FE`
- Sprint: `설정 페이지 UI 개발`
- Urgency: `High`
