### ISSUE TITLE
[Task] 읽지 않은 알림 목록 조회 API 연결

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#122]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 읽지 않은 알림 목록 조회 API 연결

# TODO
1. [X] 알림 뱃지를 클릭 시 사용자가 읽지 않은 알림 목록이 뜨도록 API 연결하여 해당 데이터를 사용자에게 제공함
2. [X] 알림 목록 UI 수정
3. [X] 알림 생성일 추가

# 소요 시간
### Labels
- Estimated time: `E: 1h`
- Group : `FE`
- Sprint: `읽지 않은 알림 목록 조회 API 연결`
- Urgency: `High`
