### ISSUE TITLE
[Task] 마이페이지 UI 개발

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#13]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 마이페이지 UI 개발

# TODO
1. [X] 사용자가 회원정보를 조회할 수 있도록 구현
2. [X]  회원 정보 수정을 원할 경우 수정 버튼을 누르고 활성화된 input 창에서 회원 정보를 수정할 수 있도록 구현
3. [X]  회원정보 수정 취소 버튼 및 적용 버튼 구현

# 소요 시간
# `0.5h`

### Labels
- Estimated time: `E: 0.5h`
- Group : `FE`
- Sprint: `마이페이지 UI 개발`
- Urgency: `High`
