### ISSUE TITLE
[Task] 프론트엔드 1차 검수 진행

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#157]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 프론트엔드 1차 검수 진행

# TODO
1. [X] 홈 화면일 경우 이전 버튼 삭제
2. [X] 모달 버튼 전체가 클릭되도록 수정
3. [X] 페이지 이동 시 스크롤 최상단에 위치하도록 구현

# 소요 시간
### Labels
- Estimated time: `E: 1.5h`
- Group : `FE`
- Sprint: `프론트엔드 1차 검수 진행`
- Urgency: `High`,
