### ISSUE TITLE
[Task] YAML profile 분리하기

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#21]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: YAML을 개발용, 운영용으로 profile 분리 적용하기

# TODO
1. [x] develop, deploy YAML 생성
2. [x] 각 profile 실행 시 문제 없이 구동되는지 확인
3. [x] 수정된 YAML BE 팀원들에게 전달

# 소요 시간
### Labels
- Estimated time: `E: 1h`
- Group : `BE`
- Sprint: `회원 관리 서비스 개발 Sprint`
- Urgency: `Low`
