### ISSUE TITLE
[Task] 서비스 설계 및 kick 선정

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#23]
# ISSUE
- Group:  `SR`
- Type: `feature`
- Detail: 기획 - 서비스 설계

# TODO
1. [x] 모티브로 가져갈 뱅크샐러드 모든 기능 탐색
2. [x] 프로젝트에 적용할 서비스 설계
3. [x] 기술 kick 선정

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `SR`
- Sprint: `SR 기획 Sprint`
- Urgency: `High`
