### ISSUE TITLE
[Task] 기능 별 우선 순위 정하기

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#27]
# ISSUE
- Group:  `SR`
- Type: `feature`
- Detail: 기능 별 우선 순위 정하기

# TODO
1. [x] Home 우선순위 정하기
2. [x] 회원 관리 서비스 우선순위 정하기
3. [x] 자산 관리 서비스 우선순위 정하기
4. [x] 가계부 관리 서비스 우선순위 정하기
5. [x] 금융 매칭 서비스 우선순위 정하기

# 소요 시간
### Labels
- Estimated time: `E: 0.5h`
- Group : `SR`
- Sprint: `SR 기획 Sprint`
- Urgency: `Low`
