### ISSUE TITLE
[Task] User Flow 작성

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#29]
# ISSUE
- Group:  `SR`
- Type: `feature`
- Detail: User Flow 작성

# TODO
1. [ ] User Flow 작성
2. [ ] User Flow 리뷰
3. [ ] User Flow 피드백 반영

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `SR`
- Sprint: `SR 기획 Sprint`
- Urgency: `Middle`
