### ISSUE TITLE
[Task] 시스템 아키텍처 작성

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#35]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 시스템 아키텍처 작성

# TODO
1. [x] 시스템 아키텍처 작성
2. [x] 시스템 아키텍처 리뷰
3. [x] 시스템 아키텍처 피드백 반영

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `SR 기획 Sprint`
- Urgency: `Low`
