### ISSUE TITLE
[Task] API 문서 작성

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#36]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: API 문서 작성

# TODO
1. [x] API 문서 작성
2. [x] API 문서 리뷰
3. [x] API 문서 피드백 반영

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `SR 기획 Sprint`
- Urgency: `Middle`
