### ISSUE TITLE
[Task] 프론트 서버 배포

### ISSUE THREAD

**Issue by powerstar13** [BithumbFarmerTeam/bitbank#40]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 프론트 서버 배포하기

# TODO
1. [x] EC2 생성 및 로드밸런서 장착
2. [x] Route 53 서브도메인 등록
3. [x] React > build 하여 배포

# 소요 시간
### Labels
- Estimated time: `E: 1h`
- Group : `BE`
- Sprint: `AWS Infra 구축 Sprint`
- Urgency: `Middle`
