### ISSUE TITLE
[Task] 로그아웃 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#41]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 로그아웃 API 개발

# TODO
1. [x] 로그아웃 API 구현
2. [x] 로그아웃 API 테스트 코드 작성
3. [x] 로그아웃 API 검수

# 소요 시간
### Labels
- Estimated time: `E: 1h`
- Group : `BE`
- Sprint: `회원 관리 서비스 개발 Sprint`
- Urgency: `Low`
