### ISSUE TITLE
[Task] 회원 탈퇴 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#42]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 회원 탈퇴 API 개발

# TODO
1. [x] 회원 탈퇴 API 구현
2. [x] 회원 탈퇴 API 테스트 코드 작성
3. [x] 회원 탈퇴 API 검수
4. [x] delDate IS NULL 만 조회하도록 Repository 적용

# 소요 시간
### Labels
- Estimated time: `E: 2h`
- Group : `BE`
- Sprint: `회원 관리 서비스 개발 Sprint`
- Urgency: `Low`
