### ISSUE TITLE
[Task] 읽지 않은 알림 개수 조회 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#43]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 읽지 않은 알림 갯수 조회 API

# TODO
1. [x] 읽지 않은 알림 갯수 조회 API 구현
2. [x] 읽지 않은 알림 갯수 조회 API Test 코드
3. [x] 읽지 않은 알림 갯수 조회 API 검수

# 소요 시간
### Labels
- Estimated time: `E: 1h`
- Group : `BE`
- Sprint: `회원 관리 서비스 개발 Sprint`
- Urgency: `Low`
