### ISSUE TITLE
[Task] 읽지 않은 알림 목록 조회 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#44]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 읽지 않은 알림 목록 조회 API 개발

# TODO
1. [x] alim --> alarm 으로 워딩 수정
2. [x] 알림 목록 조회 API 개발
3. [ ] 목록 조회 시 읽음 처리
4. [ ] 알림 목록 조회 API Test Code
5. [ ] 알림 목록 조회 API 검수

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `회원 관리 서비스 개발 Sprint`
- Urgency: `Low`
