### ISSUE TITLE
[Task] 가계부 작성 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#46]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 가계부 작성 API 개발

# TODO
1. [x] 가계부 작성 API 구현
2. [x] 가계부 작성 API 테스트 코드 작성
3. [x] 가계부 작성 API 검수

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `가계부 관리 서비스 개발 Sprint`
- Urgency: `High`
