### ISSUE TITLE
[Task] 가계부 목록 검색 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#50]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 가계부 목록 검색 API 개발

# TODO
1. [x] 프로젝트 세팅
2. [x] 라우팅 확인
3. [x] 사용자 유효성 검증 및 존재 유무 확인하는 로직 구현
4. [x] 카테고리에 따라 검색 로직 구현
5. [x] 날짜에 따라 검색 로직 구현
6. [x] 검색어에 따라 검색 로직 구현
7. [x] API Response에 맞게 데이터 가공
8. [x] 검색 결과를 최신순으로 반환

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `가계부 관리 서비스 Sprint`
- Urgency: `Middle`
