### ISSUE TITLE
[Task] 월 별 지출 통계 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#51]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 월 별 지출 통계 API 개발

# TODO
1. [x] FrontEnd에서 사용할 그래프에 필요한 데이터 구조로 API 문서 Response 수정
2. [x] 월 별 지출 통계 API 구현
3. [x] 월 별 지출 통계 API 테스트 코드 작성
4. [x] 월 별 지출 통계 API 검수

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `가계부 관리 서비스 개발 Sprint`
- Urgency: `High`

### 레퍼런스
[MySQL - 일별통계, 주간통계, 월간통계](https://bluexmas.tistory.com/626)
