### ISSUE TITLE
[Task] 소비 패턴 설문에 따른 카드 추천 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#53]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 소비 패턴 설문에 따른 카드 추천 API 개발

# TODO
1. [x] 소비 패턴 설문에 따라 카드 추천 프로세스 구현
2. [x] 카드 추천 API 구현
3. [x] 카드 추천 API 테스트 코드 작성
4. [x] 카드 추천 API 검수

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `금융 매칭 서비스 Sprint`
- Urgency: `Middle`
