### ISSUE TITLE
[Task] 인기 카드 목록 조회 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#54]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 인기 카드 목록 조회 API 개발

# TODO
1. [x] 금융 매칭 서비스 프로젝트 소스 시작
2. [x] 인기 카드 목록 조회 API 개발
3. [x] 인기 카드 목록 조회 API Test 코드 작성
4. [x] 인기 카드 목록 조회 API 검수

# 소요 시간
### Labels
- Estimated time: `E: 1,5h`
- Group : `BE`
- Sprint: `금융 매칭 서비스 개발 Sprint`
- Urgency: `Low`
