### ISSUE TITLE
[Task] 일반 회원 로그인 API 개발

### ISSUE THREAD

**Issue by boookk** [BithumbFarmerTeam/bitbank#7]
# ISSUE
- Group:  `BE`
- Type: `feature`
- Detail: 일반 회원 로그인 API 개발

# TODO
1. [x] 개발 환경 구축
2. [x] 프로젝트 구조 파악
3. [x] 데이터베이스 시험
4. [x] JWT 시험
5. [x] 데이터베이스에 토큰 저장
6. [x] Postman으로 API 작동 테스트
7. [x] 테스트 코드 작성하여 테스트 성공하기
8. [x] 리뷰 받기

# 소요 시간
### Labels
- Estimated time: `E: 3h`
- Group : `BE`
- Sprint: `회원 관리 서비스 개발 Sprint`
- Urgency: `Middle`
