### ISSUE TITLE
[Task] 가계부 검색 및 조회 UI 구현

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#71]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 가계부 검색 및 조회 UI 구현

# TODO
1. [X] 가계부 검색 서치 바 구현
2. [X] 가계부 최근 검색어 구현 (로컬스토리지 이용)
3. [X] 가계부 검색 필터 조건 구현
4. [X] 가계부 목록 조회 UI 구현

# 소요 시간
### Labels
- Estimated time: `E: 2h`
- Group : `FE`
- Sprint: `가계부 검색 및 조회 UI 구현`
- Urgency: `High`
