### ISSUE TITLE
[Task] 가계부 메인 조회 UI 구현

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#73]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 가계부 메인 조회 UI 구현

# TODO
1. [X] 가계부 메인 조회 UI 구현
2. [X] 가계부 엑셀 데이터 내보내기 & 검색 페이지 & 가계부 내역 추가 페이지 연결
3. [X]  메뉴바의 가계부에 해당 UI 연결
4. [X] 사용자의 이름 및 해당 월의 총 지출 및 소비 금액 , 가계부 내역을 조회할 수 있도록 구현

# 소요 시간
### Labels
- Estimated time: `E: 2h`
- Group : `FE`
- Sprint: `가계부 메인 조회 UI 구현`
- Urgency: `High`
