### ISSUE TITLE
[Task] 가계부 내역 추가 UI 구현

### ISSUE THREAD

**Issue by daodaoala** [BithumbFarmerTeam/bitbank#87]
# ISSUE
- Group:  `FE`
- Type: `feature`
- Detail: 가계부 내역 추가 UI 구현

# TODO
1. [X] 가계부 내역을 추가할 수 있도록 거래처명, 금액, 분류(지출/수입/이체), 카테고리, 날짜를 입력받도록 함
2. [X]  거래처명과 금액을 입력할 수 있는 INPUT 필드에 금액의 경우 천단위 마다 자동으로 (,)가 찍히도록 구현
3. [X]  분류 버튼을 클릭 시 그에 알맞는 카테고리 리스트가 뜨도록 구현
4. [X] 달력 아이콘을 클릭하면 DateTimePicker로 날짜와 시간을 선택할 수 있도록 구현

# 소요 시간
### Labels
- Estimated time: `E: 2h`
- Group : `FE`
- Sprint: `가계부 내역 추가 UI 구현`
- Urgency: `High`
